### ISSUE TITLE
$ being parsed as multiLineString segment

### ISSUE THREAD

**Issue by crmsnbleyd** [shnarazk/tree-sitter-uiua#15]
Minimal example:
```
World = "Hello"
$
World
```
in which World will be parsed as part of a string literal

**Comment by crmsnbleyd** [comment]
SInce this is an artificial example that won't come up unless someone tries to use $ as a shorthand for "", I'm completely fine with closing this

**Comment by crmsnbleyd** [comment]
An additional issue:
`¯4.5` is currently parsed as (function "¯") (number 4.5) when the high bar is also part of the number.
Thank you.

**Comment by shnarazk** [comment]
Let me consider on $string for a while...
`¯` is a monadic function, right?

```
    ∩¯ 1 2
¯2
¯1
```

**Comment by crmsnbleyd** [comment]
when directly followed by a number, it's actually part of the number literal (like -5 being a number in python). This can be verified by the colour of  ¯1 in the pad. In my emacs mode I just defined number literals as  
```
[`¯]?[0-9]+([.][0-9]+)?
```
if that's any help

**Comment by crmsnbleyd** [comment]
However, seeing it as a monadic function is also completely fine in practice, so could be okay to skip this

**Comment by shnarazk** [comment]
I fixed my wrong definition of `multiLineString` in main:HEAD.
Also, modified high-minus handling to match other tools.
They seem to work.
Thank you for reporting!
