### ISSUE TITLE
Zed build from source error

### ISSUE THREAD

**Issue by StrongTheDev** [shnarazk/tree-sitter-uiua#28]
My apologies, I didn't get enough data to show here, however, this repo throws some error when I'm trying to build Zed IDE from source.
I just commented it out from the `Cargo.toml` file in the "languages" crate of Zed, and then it finally was able to build Zed executable for linux.

>Line 77 commented out
![uiua](https://github.com/shnarazk/tree-sitter-uiua/assets/33962088/64019ced-e3c4-48e8-afc9-517a29fef74a)

On the bright side, all the other "tree-sitter" repos were downloaded successfully and threw no errors.

Again, apologies for little data

**Comment by shnarazk** [comment]
Hi,
I built Zed (main head) without any problem on Mac yesterday. And tree-sitter-uiua worked.
Today I tried github Codespaces to build it on a Linux environment, but couldn't resolve wayland dependency problem.
So, I'm sorry, but I also don't have information for now.
